// import { Montserrat } from "next/font/google";
// import localFont from "next/font/local";
import Script from "next/script";
import "../globals.css";
import "../global-fixes.css";
import HeaderSection from "../_components/HeaderSection/HeaderSection";
import FooterSection from "../_components/FooterSection/FooterSection";
import Providers from "../Providers";

// const montserratFont = Montserrat({
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
//   display: "swap",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// const georgia = localFont({
//   src: [
//     {
//       name: "Georgia",
//       path: "../../public/fonts/Georgia.woff2",
//     },
//   ],
// });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="theme-color" content="#36AEE8" />

        <title>DHI | Home</title>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossOrigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
        />

        {/* model viewer */}
        <Script
          type="module"
          src="https://ajax.googleapis.com/ajax/libs/model-viewer/3.0.1/model-viewer.min.js"
        ></Script>
      </head>
      <body
      // className={`${georgia.className} ${montserratFont.className}`}
      >
        <Providers>
          <HeaderSection />
          {children}
          <FooterSection />
        </Providers>
      </body>
    </html>
  );
}
